[phases.setup]
nixPkgs = ["python312Full", "ffmpeg", "libopus"]

[phases.install]
cmds = [
  "python3.12 -m ensurepip",
  "python3.12 -m pip install --upgrade pip",
  "python3.12 -m pip install -r requirements.txt",
  "python3.12 -m pip install opuslib"
]
