[phases.setup]
nixPkgs = ["python312Full", "ffmpeg", "libopus"]

[phases.install]
cmds = [
  "/nix/store/*-python3.12*/bin/python3.12 -m ensurepip",
  "/nix/store/*-python3.12*/bin/python3.12 -m pip install --upgrade pip",
  "/nix/store/*-python3.12*/bin/python3.12 -m pip install -r requirements.txt",
  "/nix/store/*-python3.12*/bin/python3.12 -m pip install opuslib"
]
